### ISSUE TITLE
Issue with conditional import of Base.Iterators in runtests.jl

### ISSUE THREAD

**Issue by rdeits** [tkoolen/RigidBodyDynamics.jl#169]
We saw this on @symplectomorphism 's machine. It looks like the conditional from RigidBodyDynamics.jl should be copied over into runtests.jl

**Comment by rdeits** [comment]
(this causes a failure with `Iterators not defined` when running the tests)

**Comment by rdeits** [comment]
I think this is because the newest Julia binaries are `v0.5.1-dev` which satisfies `VERSION > v0.5`, while my version of Julia is exactly v0.5.0 which does not.

**Comment by tkoolen** [comment]
Thanks!
